document.getElementById('year').textContent=new Date().getFullYear();
(async()=>{
 const safe=async(name,fallback)=>{try{return await data(name)}catch(err){console.warn(`Could not load ${name}`,err);return fallback}};
 const [s,p,e,v,people]=await Promise.all([safe('settings',{}),safe('poems',[]),safe('events',[]),safe('videos',[]),safe('people',[])]);
 const byId=id=>document.getElementById(id);
 if(byId('heroName'))byId('heroName').textContent=s.siteName||'अनुसुया साहू';
 if(byId('aboutText'))byId('aboutText').textContent=s.about||'';
 if(byId('mainQuote'))byId('mainQuote').textContent=s.quote||'';
 if(byId('institutionText'))byId('institutionText').textContent=s.institution?.description||'साहित्य, संस्कृति और रचनात्मक संवाद को समर्पित साहित्यिक संस्था।';
 [byId('yt'),byId('channelBtn'),byId('footerYoutube')].filter(Boolean).forEach(a=>a.href=s.youtube||'#');
 const logo=s.institution?.logo||s.logo;
 document.querySelectorAll('.institution-mark').forEach(mark=>{if(!logo)return;const im=document.createElement('img');im.src=logo;im.alt=`${s.institution?.name||'विश्व साहित्य सेवा संस्थान'} logo`;im.loading=mark.classList.contains('hero-institution-mark')?'eager':'lazy';im.onload=()=>mark.classList.add('has-logo');im.onerror=()=>{mark.classList.remove('has-logo');mark.textContent='VSSS'};mark.replaceChildren(im)});
 const poems=Array.isArray(p)?p.filter(x=>x.published):[],events=Array.isArray(e)?e.filter(x=>x.published):[],videos=Array.isArray(v)?v.filter(x=>x.published):[],persons=Array.isArray(people)?people.filter(x=>x.published):[];
 if(byId('poemCount'))byId('poemCount').textContent=poems.length;if(byId('eventCount'))byId('eventCount').textContent=events.length;if(byId('videoCount'))byId('videoCount').textContent=videos.length;
 if(byId('poemGrid'))byId('poemGrid').innerHTML=poems.slice(0,3).map((x,i)=>`<article class="poem-feature"><span class="poem-index">0${i+1}</span><div><div class="meta">कविता</div><h3>${esc(x.title||'अनाम कविता')}</h3><div class="poem-excerpt">${esc(x.text)}</div><a class="text-link light-link" href="poems.html">पूरी कविता ↗</a></div></article>`).join('')||'<div class="empty dark-empty">नई कविताएँ शीघ्र प्रकाशित होंगी।</div>';
 const upcoming=events.filter(x=>x.status!=='completed').sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999')).slice(0,4);
 if(byId('eventGrid'))byId('eventGrid').innerHTML=upcoming.map((x,i)=>`<article class="home-event ${i===0?'featured':''}">${x.image?`<div class="home-event-image">${img(x.image,x.title)}</div>`:''}<div class="home-event-content"><div class="event-topline"><span>${fmtDate(x.date)}</span><span>UPCOMING</span></div><h3>${esc(x.title)}</h3><p>${esc(x.venue||'')}</p><a href="events.html" class="text-link">विवरण ↗</a></div></article>`).join('')||'<div class="empty">आगामी कार्यक्रम की जानकारी शीघ्र उपलब्ध होगी।</div>';
 let featured=persons.filter(x=>x.featured);if(!featured.length)featured=persons;
 if(byId('peopleGrid'))byId('peopleGrid').innerHTML=featured.slice(0,4).map(x=>`<article class="person-home-card"><a class="person-home-photo" href="person.html?id=${encodeURIComponent(x.id)}">${x.photo?img(x.photo,x.name):'<span>✦</span>'}</a><div><span class="meta">${esc(x.role||'साहित्यकार')}</span><h3>${esc(x.nameHindi||x.name)}</h3><p>${esc(x.designation||x.country||'')}</p><a class="text-link" href="person.html?id=${encodeURIComponent(x.id)}">Know more ↗</a></div></article>`).join('')||'<div class="empty">Admin → Artists & Speakers से साहित्यकारों और अतिथियों की प्रोफ़ाइल जोड़ें।</div>';
 if(byId('videoGrid')){if(videos.length)byId('videoGrid').innerHTML=videos.slice(0,3).map((x,i)=>{let id=youtubeId(x.youtubeUrl);return id?`<article class="media-card ${i===0?'media-main':''}"><div class="media-frame"><iframe src="https://www.youtube-nocookie.com/embed/${id}" title="${esc(x.title||'YouTube video')}" loading="lazy" allowfullscreen></iframe></div><span class="meta">${i===0?'FEATURED VIDEO':'VIDEO'}</span><h3>${esc(x.title||'वीडियो')}</h3></article>`:''}).join('');else byId('videoGrid').innerHTML=`<a class="youtube-channel-card" href="${esc(s.youtube||'#')}" target="_blank" rel="noopener"><div class="play-large">▶</div><div><span class="kicker">YouTube</span><h3>कविता पाठ, साहित्यिक संवाद और सांस्कृतिक प्रस्तुतियाँ</h3><p>अनुसुया साहू के YouTube चैनल पर वीडियो देखें।</p><span class="text-link">चैनल खोलें ↗</span></div></a>`}
})().catch(err=>console.error('Homepage initialization failed',err));