
const TYPES={
 events:{title:'Events',fields:[['title','Title'],['date','Date','date'],['time','Time','time'],['venue','Venue'],['description','Description','textarea'],['registerLink','Register Link'],['image','Image','file']]},
 gallery:{title:'Gallery',fields:[['caption','Caption'],['category','Category'],['image','Image','file']]},
 poems:{title:'Poems',fields:[['title','Title'],['text','Hindi Text','textarea'],['translation','English Translation','textarea'],['image','Image','file']]},
 books:{title:'Books',fields:[['name','Book Name'],['description','Description','textarea'],['publisher','Publisher'],['purchaseLink','Purchase Link'],['cover','Cover Image','file']]},
 videos:{title:'Videos',fields:[['title','Title'],['youtubeUrl','YouTube URL']]},
 achievements:{title:'Achievements',fields:[['title','Title'],['date','Date','date'],['description','Description','textarea'],['image','Image','file']]}
};
let current='dashboard',editing=null;
const $=s=>document.querySelector(s), escA=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function localData(n){let r=await fetch(`../data/${n}.json?${Date.now()}`);return r.json()}
function status(m,bad=false){$('#status').textContent=m;$('#status').style.background=bad?'#ffd9d9':'#f2eadc'}
function switchTo(n){current=n;editing=null;document.querySelectorAll('aside button').forEach(b=>b.classList.toggle('active',b.dataset.page===n));render()}
async function render(){
 if(current==='dashboard'){let counts={};for(let n of Object.keys(TYPES)){counts[n]=(await localData(n)).length}$('#content').innerHTML=`<div class="panel"><h2>Dashboard</h2><p>Content stored in repository JSON files. Publishing commits directly through GitHub REST API.</p><div class="grid">${Object.entries(counts).map(([k,v])=>`<div class="panel"><b>${TYPES[k].title}</b><h2>${v}</h2></div>`).join('')}</div></div>`;return}
 if(current==='settings'){return renderSettings()}
 let t=TYPES[current],arr=await localData(current);$('#content').innerHTML=`<div class="top"><h2>${t.title}</h2><button class="btn" onclick="editItem()">Add New</button></div><div id="editor"></div><div class="panel">${arr.map(x=>`<div class="item"><b>${escA(x.title||x.name||x.caption||'Untitled')}</b> <small>${x.published?'Published':'Draft'}</small><div class="row"><button class="btn secondary" onclick='editItem(${JSON.stringify(x).replace(/'/g,"&#39;")})'>Edit</button><button class="btn danger" onclick="removeItem('${x.id}')">Delete</button></div></div>`).join('')||'No content yet.'}</div>`}
function editItem(x=null){editing=x;let t=TYPES[current];$('#editor').innerHTML=`<div class="panel"><h3>${x?'Edit':'Create'} ${t.title}</h3><div class="grid">${t.fields.map(f=>{let [k,l,tp='text']=f;if(tp==='textarea')return `<div><label>${l}</label><textarea id="f_${k}">${escA(x?.[k]||'')}</textarea></div>`;if(tp==='file')return `<div><label>${l}</label><input id="f_${k}" type="file" accept="image/*"><small>${escA(x?.[k]||'')}</small></div>`;return `<div><label>${l}</label><input id="f_${k}" type="${tp}" value="${escA(x?.[k]||'')}"></div>`}).join('')}</div><p><label><input style="width:auto" id="f_published" type="checkbox" ${x?.published?'checked':''}> Published</label></p><div class="row"><button class="btn" onclick="saveItem()">Save & Publish to GitHub</button><button class="btn secondary" onclick="$('#editor').innerHTML=''">Cancel</button></div></div>`;scrollTo({top:0,behavior:'smooth'})}
async function saveItem(){
 try{checkAuth();let t=TYPES[current],arr=await localData(current),now=new Date().toISOString(),obj=editing?{...editing}:{id:`${current.slice(0,-1)}-${Date.now()}`,createdAt:now};obj.updatedAt=now;obj.published=$('#f_published').checked;
 for(let [k,l,tp='text'] of t.fields){let el=$(`#f_${k}`);if(tp==='file'){if(el.files[0]){let ext=(el.files[0].name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'');let folder=current==='books'?'books':current;let path=`images/${folder}/${obj.id}.${ext}`;await GH.upload(path,el.files[0]);obj[k]=path}else obj[k]=obj[k]||''}else obj[k]=el.value}
 if(current==='poems')obj.slug=(obj.title||obj.id).toLowerCase().replace(/\s+/g,'-');
 let i=arr.findIndex(a=>a.id===obj.id);if(i>=0)arr[i]=obj;else arr.unshift(obj);await GH.put(`data/${current}.json`,JSON.stringify(arr,null,2),`Update ${current}: ${obj.title||obj.name||obj.id}`);status('Published successfully. GitHub Pages may take a short time to refresh.');editing=null;render()
 }catch(e){status(e.message,true)}
}
async function removeItem(id){if(!confirm('Delete this item from JSON? Uploaded image is not automatically removed.'))return;try{checkAuth();let a=await localData(current);a=a.filter(x=>x.id!==id);await GH.put(`data/${current}.json`,JSON.stringify(a,null,2),`Delete ${current} item`);status('Deleted and committed.');render()}catch(e){status(e.message,true)}}
async function renderSettings(){let s=await localData('settings');$('#content').innerHTML=`<div class="panel"><h2>Website Settings</h2><div class="grid">${[['siteName','Name'],['tagline','Tagline'],['heroText','Hero Text'],['quote','Quote'],['email','Email'],['phone','Phone'],['youtube','YouTube'],['about','Biography'],['education','Education'],['journey','Journey'],['mission','Mission'],['vision','Vision']].map(([k,l])=>`<div><label>${l}</label>${['about','education','journey','mission','vision'].includes(k)?`<textarea id="s_${k}">${escA(s[k]||'')}</textarea>`:`<input id="s_${k}" value="${escA(s[k]||'')}">`}</div>`).join('')}<div><label>Primary Color</label><input type="color" id="s_primary" value="${s.theme?.primary||'#7a263a'}"></div><div><label>Accent Color</label><input type="color" id="s_accent" value="${s.theme?.accent||'#c9892b'}"></div><div><label>Hero Image</label><input type="file" id="s_hero" accept="image/*"></div></div><p><button class="btn" onclick="saveSettings()">Save Settings</button></p></div>`}
async function saveSettings(){try{checkAuth();let s=await localData('settings');for(let k of ['siteName','tagline','heroText','quote','email','phone','youtube','about','education','journey','mission','vision'])s[k]=$(`#s_${k}`).value;s.theme={...(s.theme||{}),primary:$('#s_primary').value,accent:$('#s_accent').value};if($('#s_hero').files[0]){let f=$('#s_hero').files[0],ext=f.name.split('.').pop();s.heroImage=`images/hero/hero.${ext}`;await GH.upload(s.heroImage,f)}await GH.put('data/settings.json',JSON.stringify(s,null,2),'Update website settings');status('Settings published.')}catch(e){status(e.message,true)}}
function checkAuth(){let c=GH.config();if(!GH.token()||!c.owner||!c.repo)throw Error('Configure GitHub connection first.')}
function saveConnection(){let remember=$('#remember').checked,token=$('#token').value.trim();sessionStorage.removeItem('gh_token');localStorage.removeItem('gh_token');(remember?localStorage:sessionStorage).setItem('gh_token',token);localStorage.setItem('gh_config',JSON.stringify({owner:$('#owner').value.trim(),repo:$('#repo').value.trim(),branch:$('#branch').value.trim()||'main'}));status('GitHub connection saved in this browser.');}
document.addEventListener('DOMContentLoaded',()=>{let c=GH.config();$('#owner').value=c.owner||'';$('#repo').value=c.repo||'';$('#branch').value=c.branch||'main';document.querySelectorAll('aside button[data-page]').forEach(b=>b.onclick=()=>switchTo(b.dataset.page));render()});
