const GH={
 token:()=>sessionStorage.getItem('gh_token')||localStorage.getItem('gh_token')||'',
 config:()=>JSON.parse(localStorage.getItem('gh_config')||'{}'),
 headers(){return {'Accept':'application/vnd.github+json','Authorization':`Bearer ${this.token()}`,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'}},
 async request(url,options={}){let r=await fetch(url,{...options,headers:{...this.headers(),...(options.headers||{})}});if(!r.ok){let detail='';try{let j=await r.json();detail=j.message||JSON.stringify(j)}catch(e){detail=await r.text()}if(r.status===401)throw Error('GitHub authentication failed. Check or replace the PAT.');if(r.status===403)throw Error('GitHub denied this action. The fine-grained PAT needs Contents: Read and write permission for this repository.');if(r.status===404)throw Error('Repository or file was not found. Check owner, repository and branch.');throw Error(`GitHub error ${r.status}: ${detail}`)}return r},
 async test(){let c=this.config();if(!this.token()||!c.owner||!c.repo)throw Error('Owner, repository and PAT are required.');let r=await this.request(`https://api.github.com/repos/${c.owner}/${c.repo}`);let repo=await r.json();await this.file('data/settings.json');return repo},
 async file(path){let c=this.config();let r=await this.request(`https://api.github.com/repos/${c.owner}/${c.repo}/contents/${path}?ref=${encodeURIComponent(c.branch||'main')}`);return r.json()},
 async put(path,content,message){let c=this.config(),old=null;try{old=await this.file(path)}catch(e){if(!String(e.message).includes('not found'))throw e};let bytes=new TextEncoder().encode(content),bin='';bytes.forEach(b=>bin+=String.fromCharCode(b));let body={message,content:btoa(bin),branch:c.branch||'main'};if(old?.sha)body.sha=old.sha;let r=await this.request(`https://api.github.com/repos/${c.owner}/${c.repo}/contents/${path}`,{method:'PUT',body:JSON.stringify(body)});return r.json()},
 async upload(path,file){if(!file?.type?.startsWith('image/'))throw Error('Please choose a valid image file.');if(file.size>8*1024*1024)throw Error('Image is too large. Please use an image below 8 MB.');let buf=new Uint8Array(await file.arrayBuffer()),bin='';for(let i=0;i<buf.length;i+=0x8000)bin+=String.fromCharCode(...buf.subarray(i,i+0x8000));let c=this.config(),old=null;try{old=await this.file(path)}catch(e){if(!String(e.message).includes('not found'))throw e};let body={message:`Upload ${path}`,content:btoa(bin),branch:c.branch||'main'};if(old?.sha)body.sha=old.sha;await this.request(`https://api.github.com/repos/${c.owner}/${c.repo}/contents/${path}`,{method:'PUT',body:JSON.stringify(body)});return path}
};